version: "{build}"

environment:
  ELECTRON_NO_ATTACH_CONSOLE: 1

install:
  - ps: Install-Product node 6 x64
  - npm install -g npm
  - npm install -g gulp
  - npm install

platform:
  - x64

build: off

test_script:
  - npm test
