version: "{build}"

environment:
  CODE_VERSION: 1.12.2

install:
  - ps: Install-Product node 6.6.0 x64

build_script:
  - npm install
  - npm run vscode:prepublish

test_script:
  - npm test --silent
